name: Gendiff testing

on:
  push:
    branches:
      - main

jobs:
  gendiff-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run Make commands
        run: make lint test

      - name: Upload coverage to Code Climate
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        run: |
          npm install -g codeclimate-test-reporter
          codeclimate-test-reporter < coverage/lcov.info